title: 罗一鸣的个人网站
description: 大模型算法专家 | 金融科技领域开发者
show_downloads: true

baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://Gusen1453.github.io" # change this to the base hostname & protocol for your site


google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: 罗一鸣
image: /thumbnail-jumbo.png
twitter:
  username: 

plugins:
  # - jekyll-target-blank

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

target-blank:
    rel: nofollow
    add_css_classes: ext-link
    js_flag: false
    noopener: false
    noreferrer: false

header_page_refs: ['blogs', 'resume', 'about', 'contact']
